title: Cyberknight Websites
author: Julian Lopez
url: https://www.cyberknight-websites.com
description: "We are an online business seeking to serve Knights of Columbus councils and Catholic parishes for their website needs. We plan to offer website design and hosting services to help councils and parishes establish an online presence. Additionally, we shall offer a wide variety of communication services to help councils and parishes communicate with their members and the public via email, SMS, and social media."
domain: cyberknight-websites.com
permalink: /:slug

#favicon: "./arkos.png" # relative path to site's favicon

# remote_theme: abhinavs/moonwalk

theme_config:
  date_format: "%B %d %Y" # customize how date is formatted

exclude:
  - docs
  - _data/most_recent_mastodon_post.yml

highlighter: rouge

sass:
  style: :compressed

plugins:
  # - jekyll-feed
  #- jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-last-modified-at
  - jekyll-archives

# last-modified-at:
    # date-format: "%B %d %Y"

jekyll-archives:
  enabled:
    - year 
    - tags
  layouts:
    year: year
    tag: tag
  permalinks:
    year: '/posts/:year/'
    tag: '/tag/:name/'

# verbose: true

timezone: America/Los_Angeles